"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-06-06 09:25:10.584799

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import carapace.database.base

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("created_at", carapace.database.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("expires_at", carapace.database.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", carapace.database.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_auth_sessions_user"), ["user"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column(
            "data", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_jobs_enabled"), ["enabled"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_user"), ["user"], unique=False)

    op.create_table(
        "notification_subscriptions",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("expires_at", carapace.database.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column(
            "data", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user", "endpoint", name="uq_subscription_user_endpoint"),
    )
    with op.batch_alter_table("notification_subscriptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notification_subscriptions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_notification_subscriptions_user"), ["user"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(length=256), nullable=False),
        sa.Column("user", sa.String(length=256), nullable=False),
        sa.Column("channel_type", sa.String(length=64), nullable=False),
        sa.Column("channel_ref", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("created_at", carapace.database.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("last_active", carapace.database.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column(
            "state", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column(
            "sandbox_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_archived"), ["archived"], unique=False)
        batch_op.create_index("ix_sessions_channel", ["channel_type", "channel_ref"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_channel_type"), ["channel_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_favorite"), ["favorite"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_last_active"), ["last_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_pinned"), ["pinned"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user"), ["user"], unique=False)

    op.create_table(
        "users",
        sa.Column("username", sa.String(length=256), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column(
            "roles", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("created_at", carapace.database.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("updated_at", carapace.database.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("password_changed_at", carapace.database.base.UtcDateTime(timezone=True), nullable=False),
        sa.Column("last_login_at", carapace.database.base.UtcDateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_enabled"), ["enabled"], unique=False)

    op.create_table(
        "sandbox_tokens",
        sa.Column("session_id", sa.String(length=256), nullable=False),
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    with op.batch_alter_table("sandbox_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sandbox_tokens_token"), ["token"], unique=True)

    op.create_table(
        "session_audit",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=256), nullable=False),
        sa.Column("timestamp", carapace.database.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column(
            "data", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session_audit", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_audit_session_id"), ["session_id"], unique=False)

    op.create_table(
        "session_events",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(length=256), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("timestamp", carapace.database.base.UtcDateTime(timezone=True), nullable=True),
        sa.Column(
            "data", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_events_session_id"), ["session_id"], unique=False)
        batch_op.create_index("ix_session_events_session_seq", ["session_id", "seq"], unique=False)

    op.create_table(
        "session_history",
        sa.Column("session_id", sa.String(length=256), nullable=False),
        sa.Column(
            "messages", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "session_llm_requests",
        sa.Column("session_id", sa.String(length=256), nullable=False),
        sa.Column("log", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "session_usage",
        sa.Column("session_id", sa.String(length=256), nullable=False),
        sa.Column(
            "tracker", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_usage")
    op.drop_table("session_llm_requests")
    op.drop_table("session_history")
    with op.batch_alter_table("session_events", schema=None) as batch_op:
        batch_op.drop_index("ix_session_events_session_seq")
        batch_op.drop_index(batch_op.f("ix_session_events_session_id"))

    op.drop_table("session_events")
    with op.batch_alter_table("session_audit", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_audit_session_id"))

    op.drop_table("session_audit")
    with op.batch_alter_table("sandbox_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sandbox_tokens_token"))

    op.drop_table("sandbox_tokens")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_enabled"))

    op.drop_table("users")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user"))
        batch_op.drop_index(batch_op.f("ix_sessions_pinned"))
        batch_op.drop_index(batch_op.f("ix_sessions_last_active"))
        batch_op.drop_index(batch_op.f("ix_sessions_favorite"))
        batch_op.drop_index(batch_op.f("ix_sessions_channel_type"))
        batch_op.drop_index("ix_sessions_channel")
        batch_op.drop_index(batch_op.f("ix_sessions_archived"))

    op.drop_table("sessions")
    with op.batch_alter_table("notification_subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_subscriptions_user"))
        batch_op.drop_index(batch_op.f("ix_notification_subscriptions_expires_at"))

    op.drop_table("notification_subscriptions")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_user"))
        batch_op.drop_index(batch_op.f("ix_jobs_enabled"))

    op.drop_table("jobs")
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_sessions_user"))
        batch_op.drop_index(batch_op.f("ix_auth_sessions_expires_at"))

    op.drop_table("auth_sessions")
    # ### end Alembic commands ###
