apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "carapace.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
  {{- with .Values.persistence.config.finalizers }}
  finalizers:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.config.accessModes | nindent 4 }}
  {{- $storageClassName := .Values.persistence.config.storageClassName | default .Values.persistence.data.storageClassName }}
  {{- if $storageClassName }}
  storageClassName: {{ $storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
