{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "carapace.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    app.kubernetes.io/name: carapace
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
{{- end }}
